require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-performance

inherit_from:
 - .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: false

