name: "RuboCop Challenge"

on:
  schedule:
    - cron: '30 23 * * 2,3,4' # この設定の場合、火水木のAM8:30に自動でPRが作られます。

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
      - name: Install bundler
        run: gem install bundler
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Set git configuration
        run: git config remote.origin.url "git@github.com:wrozka/capybara-angular.git" # プロジェクトごとに変わる値です。
      - name: Create RuboCop challenge pull request
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec rubocop_challenger go --exclude-limit=180 --base-branch=develop --email=robot@payrollhero.com --name="Rubocop Challenger" --mode=random
